version: '3.3'

services:
  app:
    container_name: ping-dem-bot
    environment:
      - TELEGRAM_API_KEY=${TELEGRAM_API_KEY}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: my_postgres_db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
