version: '3.3'

services:
  app:
    container_name: ping-dem-bot
    environment:
      - TELEGRAM_API_KEY=${TELEGRAM_API_KEY}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_CONTAINER=${POSTGRES_CONTAINER}
      - MIGRATE=${MIGRATE}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: my_postgres_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    tmpfs:
    # This tells Docker to use in-memory storage (a temporary filesystem) for the database directory.
    # This ensures that data is not persisted to disk and is completely ephemeral.
      - /var/lib/postgresql/data