version: '3.3'

services:
  app:
    container_name: ping-dem-bot
    environment:
      - TELEGRAM_API_KEY=${TELEGRAM_API_KEY}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"